apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - env:
            - name: V2_DRIVER_IMAGE
              value: docker.io/mrdojojo/kfp-driver:master
            - name: V2_LAUNCHER_IMAGE
              value: docker.io/mrdojojo/kfp-launcher:master
          name: ml-pipeline-api-server
      serviceAccountName: ml-pipeline
